### ISSUE TITLE
Transifex still referenced in phing's build.xml

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/atom#1021]
With AtoM now being translated via https://translations.artefactual.com/ and Weblate, it should be possible to remove references to Transifex in the AtoM source. I've spotted a handful in the build.xml e.g. [here](https://github.com/artefactual/atom/blob/68629b403a2cfa2ce851b948e9a30c743f8ae5ba/build.xml#L169-L171), and a cursory search across files in the `2.6.x` branch shows some references in ~4 other files. Removing these will simplify the code-base for users and maintainers.

**Comment by jraddaoui** [comment]
Addressed in 9d6571e.
