### ISSUE TITLE
Language menu label: "português" with first letter in lower case 

### ISSUE THREAD

**Issue by ricardodepinho** [artefactual/atom#1128]
https://github.com/artefactual/atom/blob/7b2ab77cc2ac5424abb9cbc17f2df5e231b0ee73/vendor/symfony/lib/i18n/data/pt.dat#L1
Replace the first letter to Upper case in text:
s:10:"português"
with 
s:10:"Português"

**Comment by fiver-watson** [comment]
Hi Ricardo, 

Thank you for raising this issue. It has generated some interesting discussions here at Artefactual!

I've done a bit of initial investigation, and it seems this is something we are inheriting from Symfony's defaults. Looking further, it seems that, while English (and some other languages) typically capitalize proper nouns including languages, Portuguese (and others, like French, Spanish, etc) typically do not capitalize languages when writing?

If you want to make this change right now, you should be able to edit this file locally, if you clear the application cache, restart PHP-FPM, and if in use, memcached after. You may need to re-index as well. However, I haven't tested this myself yet, so make sure you test in a dev environment, and/or make a data backup first if you try this! 

In terms of implementing this change in the public project - given I'm not a Portuguese speaker, and there are also other languages in our language menu to consider, I wonder if perhaps we should try to have a broader discusson in the forum or something to solicit some other opinions first?

Cheers, 

Dan Gillean, MAS/MLIS
AtoM Program Manager

**Comment by ricardodepinho** [comment]
Hi Dan,
I'm glad for generating interesting discussions at Artefactual based on this. ;-)
I'm not the best person to answer to your questions, not even to start a boarder discussion about this. 

In my personal opinion all options on the Language menu should be in capitalized words. 
All web sites/apps I can remember of implement this, no matter what language they are on. 
At this point, the AtoM language menu with some languages capitalized and other not, it just don't look right!
And there is another problem with the AtoM language menu. The languages text should change according to the activated language. As you know, "English" in french is "Anglais" and in portuguese is "Inglês".

I've searched for a reference, and found it at the google translator language selection drop-down: 
https://translate.google.com/?hl=pt (capitalized)
https://translate.google.com/?hl=fr (capitalized)
https://translate.google.com/?hl=es (not capitalized)

Eventually our suggestion (mine and José Anjos) of changing Symfony's defaults in pt.dat for solving the problem was not the best one. I can suggest you to study other better solutions for the particular "AtoM language menu" problem.

I hope this could be of any help!
Cheers,
Ricardo Pinho

**Comment by fiver-watson** [comment]
Hi again Ricardo, 

You make a good case! Also, I suppose that not capitalizing in a sentence is different than when it is the START of a sentence - or just a single word in a menu. 

At this point we are finalizing the 2.6 release, so I suspect this will need to wait for the next release. However, at that time I will discuss this further with our team, and suggest that we make the language menu capitalization consistent. 

Thanks again!

**Comment by ricardodepinho** [comment]
Hi Dan,
That's exactly my point, that I couldn't clearly explain in english. 
My umbel suggestion to solve it could be to: **apply a capitalize function to all language names when filling the pulldown menu.** 

Regarding the other problem I mentioned, translate all language names.
**I'm afraid my suggestion could become a problem to visitors that couldn't understand the names on the language menu.** 
Imagine we enter an AtoM site with chinese default language. How could we find the English or Portuguese option?! ;-)
Unless we could complement the language name with an international symbol (like a flag image). 
So, for now, probably the best is to keep the language menu as it is and eventually only capitalize all names by default.
My umbel contribution.
And keep up the good work!
Cheers!

**Comment by mInnes-archives** [comment]
Hey @ricardodepinho, see a simple proposed solution in #1302.

**Comment by ricardodepinho** [comment]
Thanks @mInnes-archives . Excellent!
I will give it a try ASAP.
Cheers

**Comment by mInnes-archives** [comment]
@fiver-watson, this issue is probably safe to close now.
