### ISSUE TITLE
500 error when trying to manage Accessions

### ISSUE THREAD

**Issue by xojc** [artefactual/atom#1199]
When attempting to browse the Accession listings, I receive a status 500 in my browser and the following in the nginx error log:

> 2020/09/29 18:37:04 [error] 574#574: *60 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ',' in /usr/share/nginx/atom/plugins/qtAccessionPlugin/modules/accession/actions/browseAction.class.php on line 125" while reading response header from upstream, client: 10.10.10.1, server: _, request: "GET /accession/browse HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.atom.sock:", host: "10.10.10.10", referrer: "http://10.10.10.10/taxonomy/list"

**Comment by fiver-watson** [comment]
We've created an ticket in our issue tracking system to track this here: https://projects.artefactual.com/issues/13429

Closing this issue; the Artefactual team will push a corresponding fix referencing the internal ticket. 

Thanks again for bringing this to our attention!
