### ISSUE TITLE
The index functions associated with bulk updating publication status do not get initialized with a language code to be able to read title into the index

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/atom#1211]
The index functions associated with bulk updating publication status do not get initialized with a language code to be able to read title into the index. NB. for the casual reader, this makes the search results look pretty bad - but it doesn't affect what is retrieved for the archival description.

For example, initial import (doesn't matter if it is Draft or Published) looks as follows:

![image](https://user-images.githubusercontent.com/1880412/97824359-ad635e80-1c89-11eb-905a-a2c69564baa5.png)

After running the update publication status task we see the following:

![image](https://user-images.githubusercontent.com/1880412/97824411-d4ba2b80-1c89-11eb-9ee3-f3f30b83e30d.png)

Various fields are not correctly read and output in the ES index here. 

![image](https://user-images.githubusercontent.com/1880412/97826010-6e83d780-1c8e-11eb-9fd3-e90231191029.png)

The correct output should normally look something like: 

Vs. 

![image](https://user-images.githubusercontent.com/1880412/97826153-d1756e80-1c8e-11eb-9f22-334630d55161.png)

_Docker commands used:_

* `docker-compose exec atom php symfony tools:purge --demo`
* `docker-compose exec atom php symfony csv:import --source-name=un /home/www-data/error-demo-draft.csv --index`
* `docker-compose exec atom php symfony tools:update-publication-status published a-simple-title`

_Test CSV:_

[error-demo-draft.zip](https://github.com/artefactual/atom/files/5472570/error-demo-draft.zip)

**What are we seeing in the code**

* [updatePublicationStatusTask](https://github.com/artefactual/atom/blob/487c9ddf6144fb2a4caad05665c9e60e25e9cc77/lib/task/tools/updatePublicationStatusTask.class.php#L47-L51) is the primary runner for this work.
* [arElasticSearchModelBase](https://github.com/artefactual/atom/blob/487c9ddf6144fb2a4caad05665c9e60e25e9cc77/plugins/arElasticSearchPlugin/lib/model/arElasticSearchModelBase.class.php#L76-L79) is the code run by both the initial CSV import and the update task to add data to the ES index. We never progress far enough into this [loop](https://github.com/artefactual/atom/blob/487c9ddf6144fb2a4caad05665c9e60e25e9cc77/plugins/arElasticSearchPlugin/lib/model/arElasticSearchModelBase.class.php#L106-L109) because `$allowedLanguages` is never set. 
* [QuitbitSetting](https://github.com/artefactual/atom/blob/487c9ddf6144fb2a4caad05665c9e60e25e9cc77/lib/model/QubitSetting.php#L114) is the place where the `ii18n` value should be read into the settings. 

It looks like the bulk publication task [hasn't been updated in a while](https://github.com/artefactual/atom/commits/qa/2.x/lib/task/tools/updatePublicationStatusTask.class.php) so this might go back a few versions of AtoM.

**Comment by jraddaoui** [comment]
Moved to https://projects.artefactual.com/issues/13434

Thanks @ross-spencer!
