### ISSUE TITLE
Problem: Clipboard data NOT purged when 'SAVED CLIPBOARD MAXIMUM AGE' is set to default value of '0'

### ISSUE THREAD

**Issue by currmie** [artefactual/atom#1218]
**Expected behaviour**
By default, the clipboard data should be purged by the following day.

**Current behaviour**
Clipboard data remains cached; cron job does not appear to be working as expected.

**Steps to reproduce**

1. Without clearing my browser cache, I add multiple items to clipboard.

1. Additionally, I save content to multiple clipboard IDs.

1. Wait until next day to verify whether data remains on clipboard.

Content is still there. This is true for both public and authenticated users.

**Your environment (version of Archivematica, operating system, other relevant details)**

Tested on v 2.5.3 - 172.

Question from Support team: Is this an implementation issue or a docs issue?

---

**For Artefactual use:**

Before you close this issue, you must check off the following:

- [ ] All pull requests related to this issue are properly linked
- [ ] All pull requests related to this issue have been merged
- [ ] A testing plan for this issue has been implemented and passed (testing plan information should be included in the issue body or comments)
- [ ] Documentation regarding this issue has been written and merged (if applicable)
- [ ] Details about this issue have been added to the release notes (if applicable)

**Comment by jraddaoui** [comment]
Moved to https://projects.artefactual.com/issues/13442, thanks @currmie!
