### ISSUE TITLE
REST API ?

### ISSUE THREAD

**Issue by raqqun** [artefactual/atom#1259]
Hi there does atom support a REST API ? Is there a possibility to write one as a plugin ?

Thank you

**Comment by fiver-watson** [comment]
Hi @raqqun. In the future, general questions like this are best asked in our user forum, where both Artefactual staff and other community members can respond, and where others can see the answers as well, in case they have similar questions. See: 

* https://groups.google.com/g/ica-atom-users

AtoM does have a very limited REST-like API at present, with only a few endpoints for reading, not writing. See: 

* https://www.accesstomemory.org/docs/latest/dev-manual/api/api-intro/

These are already managed via the `arRestApiPlugin`, and could certainly be expanded with further development. We have a number of development resources on our wiki, here: 

* https://wiki.accesstomemory.org/Development#Development_resources

Cheers, 

Dan Gillean, MAS, MLIS
AtoM Program Manager, 
Artefactual Systems
