### ISSUE TITLE
LDAP access using the AD attribute sAMAccountName

### ISSUE THREAD

**Issue by daniel0405-sys** [artefactual/atom#1296]
Helo! 

Is it possible to change ldapUser.class.php to authenticate using the Active Directory attribute sAMAccountName?

**Comment by sbreker** [comment]
Hi Daniel

I am not familiar with your specific AD structure and the attribute 'sAMAccountName', but if your users share a common Base DN, and 'sAMAccountName' is unique at that level, then it could work. AtoM's Base DN and Bind Lookup Attribute would need to be set correspondingly.

AtoM's LDAP Settings page allows configuration of:

- Host: hostname or IP of the LDAP server
- Port: the default port is 389
- Base DN: This is the base distinguished name (this is the AD node where the users are found - all users need to have the same Base DN)
- Bind Lookup Attribute: This is the field that the AtoM username being authenticated will be found in. By default this is 'uid' in AtoM, but can be set to other valid values like 'cn' or possibly 'sAMAccountName'.

For general questions like this please consider asking in the AtoM user forum which can be found here:
https://groups.google.com/g/ica-atom-users

Steve
