### ISSUE TITLE
Problem: Physical object CSV import unit test failing in Windows

### ISSUE THREAD

**Issue by djjuhasz** [artefactual/atom#1323]
### AtoM version
qa/2.x (2e2ce4a)

### Installation environment
Docker compose environment (Docker Desktop for Windows v20.10.7; PHP 7.4.20 (cli); Percona 8.0.22-13; Elasticsearch v5.6.16; Windows 10 Home, version 2004)

### Steps to reproduce the issue

1. Run the PHPunit test suite:
```
docker-compose exec atom composer test
```

###  The resulting error 
```
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

...........................F...................................  63 / 165 ( 38%)
............................................................... 126 / 165 ( 76%)
.......................................                         165 / 165 (100%)

Time: 00:00.081, Memory: 20.00 MB

There was 1 failure:

1) PhysicalObjectCsvImporterTest::testSetFilenameFileUnreadableException
Failed asserting that exception of type "sfException" is thrown.

FAILURES!
Tests: 165, Assertions: 400, Failures: 1.
Script phpunit handling the test event returned with error code 1
```

### Expected outcome

All tests should pass

**Comment by jraddaoui** [comment]
Thanks @djjuhasz,

This is more related to the Docker environment than Windows, I created [this Redmine ticket](https://projects.artefactual.com/issues/13492) a while ago, but this raises another issue about the containers running by the root user. 

Also, I'm a big fan of using Github issues but, have you discussed creating this in here with someone? @fiver-watson still uses Redmine for the release notes and ticket list and, while one could argue if this should go to the release notes, I believe we have been including this kind of changes in there.

**Comment by djjuhasz** [comment]
@jraddaoui oh great, I'll use the Redmine ticket number instead.

I haven't discussed using Github issues with anyone, but at this point projects.artefactual.com is so slow that I find it really annoying to use it. 😬   I was hoping to get by without a Redmine ticket on this one because it has nothing to do with the actual functionality of the software, it's just a glitch in the unit test.
