### ISSUE TITLE
Question: multiple instances sharing same code-base

### ISSUE THREAD

**Issue by jcharaoui** [artefactual/atom#1443]
Hello, I'd like to know if it's possible to run multiple independent instances of AtoM on a signle server, sharing the same code-base? Have other users deployed AtoM in a similar configuration? What would be required? Thanks.

**Comment by fiver-watson** [comment]
Hi @jcharaoui, it is possible to run multiple AtoM instances on a single server. However, it's not possible for them to share the same code base - you'd need separate installations on a single server. There is no way, for example, to specify a different connection to MySQL's database or the Elasticsearch index based on the domain. There are a number of configuration parameters like this that would need their own independent values that cannot currently be shared.

If you have further questions, I recommend posting them in the AtoM user forum, where other users might share their experiences and workarounds with you! See: 

* https://groups.google.com/g/ica-atom-users
