### ISSUE TITLE
Hardcoded key value in InformationObject browseSuccess

### ISSUE THREAD

**Issue by bardocuteam** [artefactual/atom#1541]
Hi,
In InformationObject's browseSuccess template, the value of "Hierarchy" is hard coded, c.f. [this line](https://github.com/artefactual/atom/blob/qa/2.x/apps/qubit/modules/informationobject/templates/browseSuccess.php#L167).
Other templates, e.g. [this one](https://github.com/artefactual/atom/blob/953edc0e1084c54aaf2b9b68dfd001c13db57658/apps/qubit/modules/informationobject/templates/_treeView.php#L115), make correct use of the translation key.
Cheers,
Raphaël

**Comment by fiver-watson** [comment]
Hi @bardocuteam!

Thanks for this. I have reproduced the issue locally and confirmed your report. For now, the AtoM team is still using Redmine to track issues, so I have filed an issue for this there: 

* https://projects.artefactual.com/issues/13630

In light of this, I am going to close this GitHub issue now, as we'll track future progress on this via the Redmine ticket. 

Thanks again!
