### ISSUE TITLE
Redmine housekeeping

### ISSUE THREAD

**Issue by mInnes-archives** [artefactual/atom#1550]
I was reorienting myself with the Redmine site and found a couple of open bugs that should be safe to close. I figured this would be the easiest place to flag these.

## Bug 13472

_Creating accession record via GUI and populating creator field results in duplicate creator authority records, anomalies_

[https://projects.artefactual.com/issues/13472](url)

This was resolved as part of #1276. I've confirmed that it behaves as it should.

## Bug 2430

_Max reference image width ignored_

[https://projects.artefactual.com/issues/2430](url)

This setting value does apply to reference images, but not as max width. It reflects the maximum number of pixels on the longest edge which can be either width or height. This behaviour was properly clarified in the setting text in #1245.

For the sake of interest, I'm pretty sure [this line](https://github.com/artefactual/atom/blob/47d3d8b97dc4789a942288e98465e99abb40fa72/lib/model/QubitDigitalObject.php#L2328) is what causes the longest edge behaviour.

**Comment by fiver-watson** [comment]
Thanks! Done. TBH there's a lot more cleanup needed in Redmine, but it helps to be able to close some old outstanding issues!
