### ISSUE TITLE
Cant add bosnian language , and it is full translated

### ISSUE THREAD

**Issue by superhik45** [artefactual/atom#1565]
Cant add bosnian language , and it is full translated

**Comment by fiver-watson** [comment]
Hi @superhik45 , thanks for your report. We have also discovered this issue, and filed a ticket in our official issue tracking system - you can see the issue ticket here: 

* https://projects.artefactual.com/issues/13639

We hope to follow up on this issue soon in an upcoming point release. In the meantime, if we discover any workarounds that will allow you to use Bosnian immediately, we will let you know. My sincere apologies for the delay and frustration. 

I will close this issue now, as we will track progress via [ticket 13639](https://projects.artefactual.com/issues/13639) going forward.
