### ISSUE TITLE
Problem: Indexing inherited creators introduces a lot of noise to search results

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom#1598]
### Current Behavior

Currently we are indexing inherited creator names and histories as part of the information object search index mapping. One result of this is that when a term appears in a creator's history on their actor record, ALL descriptions in a linked hierarchy (including those where the creator is inherited) are returned when a unique term from the actor history is searched in the global search box. 

This is confusing since the searched term does not appear anywhere on the returned records where the creator is inherited. Consequently, finding directly relevant results becomes quite difficult, and almost every search returns far more results than is helpful or necessary, without providing end users a clear and visible reason why the result is returned. 

**Steps to reproduce the behavior**

* Find or create an archival unit with many different levels of description. For testing, ensure that:
  * There is only one creator, added to the top-level description (and therefore inherited throughout)
  * There are no other creators added at lower levels
  * The creator is not linked to any other archival units
* Edit the creator and add a unique term to the history - e.g. `fubar`
* Save, and wait for reindexing job to complete successfully
* Search `fubar` in the global search

### Expected Behavior

* The top-level record where the creator is directly linked is returned (since the term appears in the history, and the history is displayed directly in the description
* No other information objects are returned when performing a global search for a unique term that only appears in a creator's history. 
* Search results are only shown if the related records clearly show the target search term

### Possible Solution

Consider removing the following from the search index mapping: 

* https://github.com/artefactual/atom/blob/qa/2.x/plugins/arElasticSearchPlugin/config/mapping.yml#L497-L500
* https://github.com/artefactual/atom/blob/qa/2.x/plugins/arElasticSearchPlugin/config/mapping.yml#L544-L552

(plus whatever other changes are needed to ensure that indexing doesn't break when these elements are removed from the mapping). 

In essence, consider removing inherited creator information from the information object search results.

### Context and Notes

First reported in the user forum, 2023-05-17: 

* https://groups.google.com/g/ica-atom-users/c/cS80eqn6Gr0/m/qIJTVuR1AQAJ

Confirmed in local testing *2023-05-18, using the 2.7.0.3 Vagrant box running stable/2.7.x) that a term added to a creator history, when searched in the global search box, will return all results from an archival unit that has that creator linked via inheritance.

We attempted to simplify the search index and reduce noise previously in [Redmine 13386](https://projects.artefactual.com/issues/13386). However, I think this is worth revisiting and reviewing further. 

There are other fields we are currently indexing for information objects that will not be displayed in the related records. For example: does it make sense to keep indexing alternative/standardized/other forms of name for any linked actors, when these do not appear in the linked IOs? I believe the rationale at the time was to potentially help researchers account for the difference in popular names vs what might be used on an authority record - e.g. Mark Twain vs Samuel Clemens, David Bowie vs David Robert Jones, etc. However, on reflection: in most of these cases, the more well-known name is likely to appear in the actor history or the fonds scope and content anyway, so does it add anything to possibly return results that don't include the searched term by indexing these additional name forms?

This is just one example. I would encourage the Maintainers and product owner(s) to do further testing and analysis. In the meantime, I think just removing the inherited creators from the IO index would help a lot in reducing search result noise. 

### Version used

stable/2.7.x - post 2.7.1 release

### Operating System and version

Ubuntu 20.04

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by fiver-watson** [comment]
Suggested workaround from a community member [via the AtoM User Forum](https://groups.google.com/g/ica-atom-users/c/cS80eqn6Gr0/m/K4cwZajCAAAJ), until a formal fix for this is available: 
>
> As a temporary fix, if you edit `/plugins/arElasticSearchPlugin/config/mapping.yml` by adding a property to the inherited_creators after line 547:
>
> https://github.com/artefactual/atom/blob/qa/2.x/plugins/arElasticSearchPlugin/config/mapping.yml#L547
>
> so that it now reads

```
        properties:
          i18n: { type: object, dynamic: true, include_in_all: false }
          id: { type: integer }
```

> then reindex and clear the caches, that should keep those inherited fields out of the search results.

**Comment by Jimadine** [comment]
The workaround works well for us. Just to mention, in our production environment I had to run `systemctl status php7.4-fpm` as a final step. This wasn't required in our little-used test environment.

**Comment by anvit** [comment]
Planning to remove only the mapping for inherited creator history to remove the results which match keywords that match keywords in an inherited creator's biographical history rather than getting rid of results that match inherited creators altogether.

Removing them altogether might make the results less noisy, but this might lead to some confusion for some users since there might be the expectation for some that a result should show up if the name appears on a description page, which is the case for inherited creators names.
