### ISSUE TITLE
Regression: Escape special characters setting no longer working in 2.7.x

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom#1605]
### Current Behavior

This issue was first reported in the user forum 2023-03 but not confirmed at the time to be a 2.7 issue. Recently re-reported by another user upgrading from 2.4 (where the setting worked), and reproducible in the public demo site (now running 2.7.1-v192). Forum thread: 

* https://groups.google.com/g/ica-atom-users/c/OTTzqjQTcMk/m/K0lxHczaAgAJ

**Steps to reproduce the behavior**

* Login as an administrator
* Create a description that includes a slash - e.g. `coffee/tea`. 
* Perform a search for `coffee/tea`: this should produce an Elasticsearch exception
* Navigate to Admin > Settings > Global, and find the "Escape special chars from searches" setting
* Add `/` to this setting's input and Save
* Perform the global search for `coffee/tea` again

**Error encountered**

Elasticsearch exception is thrown. No search results returned. 

### Expected Behavior

* After adding the slash to the escaped characters setting, no Elasticsearch error should be thrown
* The setting should remove the reserved character before using it as a search string, essentially searching `coffee AND tea`

### Possible Solution

Check for regressions introduced in 2.7... or possibly even 2.6.x? 

### Version used

AtoM 2.7.1 - v192

### Operating System and version

Ubuntu 20.04

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by hggsilva** [comment]
I tested it today in a 2.6.2 instance and it still works.
I don’t know whether it also works in 2.6.3 and 2.6.4.
