### ISSUE TITLE
Feature: A tab for viewing failed jobs

### ISSUE THREAD

**Issue by anvit** [artefactual/atom#1613]
Users would find it helpful to be able to filter and see only failed jobs in AtoM. 

In the Jobs page (after logging in, visit `Manage > Jobs` from the menu), we currently have an "All jobs" filter/tab, and a "Active jobs" filter/tab, but there's no easy way to filter and and see  failed jobs.

Another tab should be created in the browse page (`apps/qubit/modules/jobs/templates/browseSuccess.php` https://github.com/artefactual/atom/blob/d996e1c4a0ab802c9900ab7b789f04d3960ad2f9/apps/qubit/modules/jobs/templates/browseSuccess.php#L4-L7), similar to how we have a tab for active jobs, and the corresponding filter should be handled in the browse action (`apps/qubit/modules/jobs/actions/browseAction.class.php` https://github.com/artefactual/atom/blob/d996e1c4a0ab802c9900ab7b789f04d3960ad2f9/apps/qubit/modules/jobs/actions/browseAction.class.php#L53-L60).

**Comment by melaniekung** [comment]
Example csv to trigger failed job:
[failure.csv](https://github.com/artefactual/atom/files/12652684/failure.csv)

**Comment by melaniekung** [comment]
PR merged to this commit: Add tab for viewing failed jobs (https://github.com/artefactual/atom/issues/1613) (https://github.com/artefactual/atom/pull/1658)
