### ISSUE TITLE
Set arDominionB5Plugin to be the default theme for new installations in AtoM

### ISSUE THREAD

**Issue by anvit** [artefactual/atom#1632]

**Comment by anvit** [comment]
Tests are failing on making this change. Will need to investigate to see if changes need to be made to have them complete successfully.

**Comment by jraddaoui** [comment]
Tests fixed in https://github.com/artefactual/atom/pull/1637/commits/9454ef74e37f5b1d081e13c80513f64dcc22cae1.

**Comment by anvit** [comment]
Thanks @jraddaoui!
