### ISSUE TITLE
Regression: Global search institutional delimiters and advanced search link no longer working

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom#1635]
### Current Behavior

**Steps to reproduce the behavior**

1. Ensure you are using the default BS2 theme (notes on BS5 behavior below)
2. Navigate to Browse > Archival institutions
3. Click through to the view page of an institution
4. If desired, select a description from the holdings list and click through there as well to the view page
5. Now click into the global search box

**ISSUE 1:** No institutional delimiter radio button appears, allowing a user to limit searching to the most recent repository. The search is only global. 

6. Click on the "Advanced search" link in the global search drop-down menu: 

**ISSUE 2:** Page reloads, but the Advanced search menu is not expanded

### Expected Behavior

* The institutional search delimiter should appear when clicking into the global search box after visiting an archival institution
* Clicking on the Advanced search link in the global search drop-down should reload the page with the Advanced search section expanded - and possibly in focus as well (i.e. cursor in first adv search field)?

### Context and Notes

First reported in the AtoM user forum, 2023-07-12: https://groups.google.com/g/ica-atom-users/c/VcfuqlXxC4M/m/yqqY_vL1AQAJ

Reproduced in the public demo site. The missing functionality is described further in the documentation here: 

* https://www.accesstomemory.org/docs/2.7/user-manual/access-content/search-atom/#search-box-delimiters

**BS5 behavior**

The institutional delimiter IS present in the BS5 theme. However, this might be an opportunity to revisit the UX on this. With the change introduced in BS5, the delimiter options are now hidden in the gear menu next to the global search, and not immediately visible in the drop-down when clicking into the search field. This could mean that defaulting to the institutional delimiter (i.e. automatically scoping the next search to a single institution rather than globally) after a user visits an archival institution view page or the view page of a linked description could be confusing, and result in users not finding expected results. 

At minimum I would suggest going forward that with this design choice, the search should  ALWAYS remain global by default, UNLESS a user clicks open the drop-down and sets it themselves. We should not be scoping user searches without visual feedback in advance. The other option  is to make some UI changes to make the delimiters more immediately visible, rather than hidden in a separate drop-down menu.

The advanced search link in this new global search drop-down menu also does not work as expected in BS5 - the advanced search menu is not expanded when the link is clicked and the page reloads. 

### Version used

AtoM 2.7.2 - 192

### Operating System and version

Ubuntu 20.04

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by fiver-watson** [comment]
**Additional issue found**

The "Advanced search" link in the global search drop-down no longer opens the search page with the Advanced search panel open. This doesn't work in both BS2 and BS5 themes. 

Normally when clicking on the link, some parameters are added to the browse page url: 

`/informationobject/browse?showAdvanced=1&topLod=0`

It is the `showAdvanced=1` parameter that is not working here. 0 should mean keep the panel collapsed; 1 typically means expand it on page load. 

Reproduced on the public demo site currently running 2.7.3 - 192

**Comment by anvit** [comment]
Other than fixing the two listed issues, I'm planning on updating the BS5 theme search box's behaviour to be closer to how the BS2 does things (show search options on focusing in the search input field, and no separate button for search option dropdown), with one major difference - search options would always be visible in the BS5 dropdown, and if autocomplete has some matching entries, the search options would be shown below them.

Also planning on updating the default search to be global (for both BS2 and BS5 themes).

**Comment by jraddaoui** [comment]
Just noting that we moved the institutional drop-down outside of the input drop-down for accessibility reasons. We should test these changes in that regard, specially keyboard navigation and screen readers.

**Comment by anvit** [comment]
Had a chat with @jraddaoui about some accessibility concerns, and a couple of them still remain if we merge the drop down with search options, the major ones being:

- Arrow key navigation within the drop down will end up going into the search options, which would be confusing behaviour.
- We'd also lose the labelled-by aria attribute, which would make this confusing for screen readers.

For now, going with making global the default search option seems like the best option given the accessibility concerns.
