### ISSUE TITLE
Regression: media-type option on digital object deriv regeneration task no longer works

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom#1643]
### Current Behavior

As part of release 2.6.0 and in preparation for the replacement of the legacy Flash-based media player, [Feature #12903](https://projects.artefactual.com/issues/12903) was developed, adding a new `--media-type` option to the digital object derivatives regeneration task. This option allows users to specify a media type (e.g. audio, video, image, text, other) and limit regeneration of DO derivatives to just the selected type.

...in theory. At present, in qa/2.x (post 2.7.3 release), this option is no longer working as intended. 

First [reported in the AtoM user forum](https://groups.google.com/g/ica-atom-users/c/1BzCWX8DO-w/m/Ky8HEaR-AQAJ) 2023-08-14; reproduced by DG in the AtoM-Docker local test env (on qa/2.x) 2023-08-16.

**Steps to reproduce the behavior**

1. Make sure you have some archival descriptions in your test environment with digital objects of a few different media types attached (e.g. images, video, etc)
2. Run the task using the `--media-type` option to limit the generation to video:

```
php symfony digitalobject:regen-derivatives --media-type="video"
```

## Error encountered

The task generates derivatives for ALL digital objects, rather than just the selected media type. Sample output from local testing: 

```
dgillean@fiver-work:~/Desktop/atom-docker/atom$ DS digitalobject:regen-derivatives --media-type="video"
                                                                             
  Continuing will regenerate the derivatives for video digital objects       
  This will PERMANENTLY DELETE existing derivatives you chose to regenerate  
                                                                             
  Continue? (y/N)                                                            
                                                                             
y
>> digital object Regenerating derivatives for dibujo_animado_lindo_de_tocino_y_del_huevo_tarjeta_postal-rd9d6d99a0833431cbd8a6655ad6d3725_vgbaq_8byvr_324.jpg... (1.81s)
>> digital object Regenerating derivatives for il_340x270.473520073_izfa.jpg... (2.63s)
>> digital object Regenerating derivatives for weird_wonderful_bunnies_rabbit_asleep.jpg... (3.09s)
>> digital object Regenerating derivatives for bunny-bow.jpg... (3.66s)
>> digital object Regenerating derivatives for fox-bunny.jpg... (3.93s)
>> digital object Regenerating derivatives for NomNomNom.jpg... (4.2s)
>> digital object Regenerating derivatives for sassy-bunny.jpg... (4.37s)
>> digital object Regenerating derivatives for the_tiniest.jpg... (4.55s)
>> digital object Regenerating derivatives for sample-mp4-file.mp4... (4.91s)
>> digital object Please update the search index manually to reflect any changes
>> digital object Done!
```

### Expected Behavior

AtoM will only regenerate the digital object derivatives for the selected media type

### Context and Notes

See documentation for the related task here: 

* https://www.accesstomemory.org/docs/latest/admin-manual/maintenance/cli-tools/#regenerating-derivatives

### Version used

qa/2.x - AtoM settings page reads: 2.8.0 - 193

### Operating System and version

Docker env 

### Default installation culture

en

### PHP version

7.4

**Comment by anvit** [comment]
My guess is that the query [here](https://github.com/artefactual/atom/blob/7b7ffdb474586adad6dd4c6eea1493bd75db5b53/lib/task/digitalobject/digitalObjectRegenDerivativesTask.class.php#L199) is malformed, and the condition for media-types doesn't end up after the where clause.
