### ISSUE TITLE
Problem: Issue adding access points

### ISSUE THREAD

**Issue by amayita** [artefactual/atom#1661]
### Current Behavior

Problem adding access points:

If you start to type a term, then decide not to add it and delete the bullet point before saving the archival description, the incomplete term is still saved in the taxonomy.

See attached image.

To replicate:

Menu "Add" → "Archival description"
Start typing in "access points" → "place access points"
Click anywhere outside ‘place access points’ text box; a bullet point will appear next to the text you have typed
Click "bullet point" (which becomes cross) to delete text
Save archival description
Check "places taxonomy" – incomplete text will appear as a term

### Expected Behavior

The incomplete term should not get created as a taxonomy

### Version used

AtoM 2.7.3

### Operating System and version

Ubuntu 20

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by melaniekung** [comment]
Note that the issue occurs for all access points (place, subject, name, and genre) and is not template specific (ISAD and RAD have been tested to reproduce the same bug).
