### ISSUE TITLE
Problem: Docker gives an error when it is trying to install a package from npm

### ISSUE THREAD

**Issue by arthurd2** [artefactual/atom#1662]
Hi People, 
I guess theres a typ0 in the Dockerfile in the following line: https://github.com/artefactual/atom/blob/9fd22ace13c16132d1b73f639c08f445ade02bd7/Dockerfile#L54

In order to work, we need to remove the second `npm` in the line.

**Comment by anvit** [comment]
Thanks so much for reporting this @arthurd2!

**Comment by melaniekung** [comment]
PR: https://github.com/artefactual/atom/commit/43a18e155077ffc69350598d861222424272df4b
