### ISSUE TITLE
Problem:  ElasticSearch 5.x dependency

### ISSUE THREAD

**Issue by wioxjk** [artefactual/atom#1708]
### Current Behavior

ElasticSearch 5.0 was released in 2016, and has been End of Life since many years.

### Expected Behavior

Support for Non-EOL products like ES7 and ES8

**Comment by LlGC-ild** [comment]
Hi - this is becoming quite an issue for us now. Has there been any investigation into how much work re-coding for a supported ES would be?

**Comment by LlGC-ild** [comment]
Sorry, I've now seen discussions on the Google Group etc which provide much more info on this. Target for v2.9 I understand.

**Comment by anvit** [comment]
Upgraded ElasticSearch and Elastica to 6.x, and made some changes to the arElasticSearch plugin that will allow the new versions to work with AtoM.
