### ISSUE TITLE
Problem: CSV GUI export logs wrong number of items exported.

### ISSUE THREAD

**Issue by melaniekung** [artefactual/atom#1759]
### Current Behavior

**Steps to reproduce the behavior**
1. Export a description with translations to CSV
2. Logs show rows exported instead of items/records exported.

### Expected Behavior

Logs should report 1 item/record exported for each description, not each language exported.

**Comment by fiver-watson** [comment]
one thought - it might be useful to show both counts? like `10 records comprising 16 rows of data exported`, or similar. Just an idea!
