### ISSUE TITLE
AtoM 2.7.3 spelling error in EAC xml

### ISSUE THREAD

**Issue by KelliBee123** [artefactual/atom#1768]
### Current Behavior

Hi Artefactual, this EAC error was reported by an Archeion member institution:

**Steps to reproduce the behaviour**
1. Go to any authority record with subject access points ([example](https://www.archeion.ca/congregation-of-sisters-of-st-joseph-london))
2. Click on "EAC" export to view the EAC xml for the authority
3. Find the <localControl> field and note that in the nested <term> tag the "vocabularySource" attribute is spelled "vocalularySource" ([example](https://www.archeion.ca/congregation-of-sisters-of-st-joseph-london;eac?sf_format=xml))

I believe the vocabularySource field should be in the <localControl> tag and not the <term> tag from looking at the EAC documentation for [localControl](https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-localControl) and [term](https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-term) - but it's not 100% clear from the EAC documentation examples and allowed attributes list for <term>.

When I try to [validate AtoM EAC files](https://saa-sdt.github.io/eas-validator/) I also get a [namespace error](https://saa-sdt.github.io/eas-validator/?url=https%3A%2F%2Fwww.archeion.ca%2Fcongregation-of-sisters-of-st-joseph-london%3Beac%3Fsf_format%3Dxml&version=2.0). 

I'll look into the namespace error and poke around on the Google Group to see if this has come up before before filing an issue about the namespace validation issue. 

Thanks!

### Expected Behavior

In the EAC xml the "vocalularySource" attribute should be spelled "vocabularySource" .

### Version used

AtoM 2.7.3

### Contact details

kelli.babcock@gmail.com

**Comment by sallain** [comment]
Thanks for filing this issue @KelliBee123! @anvit has tagged it for 2.8.1 so expect to see it in that release!
