### ISSUE TITLE
Problem: Sword DIP upload jobs report success but nothing happens

### ISSUE THREAD

**Issue by Sunday-Crunk** [artefactual/atom#1778]
### Current Behavior

**Steps to reproduce the behavior**
1. Instantiate fresh AtoM 2.8x system
2. Enable rest and sword plugins, ensure rest of AtoM configuration is set to receive DIP uploads via sword
3. Configure AtoM sword deposit directory to address tmp directory cleanup bug
4. Restart worker, cleanup and reboot
5. Create a target record, I will create one with the slug "photograph-album"

5a. Configure a fresh Archivematica 1.15 installation with the necessary options to facilitate sword DIP uploads to AtoM (user info, rsync where required)
5a-2. Process a transfer through ingest until DIP upload, select 'upload to AtoM'
5a-3. Enter our slug 'photograph-album'
5a-4. Confirm Archivematica has successfully fulfilled it's end by presence of "AtoM picking up async in the job scheduler" log and DIP upload microservice success.
5a-5. Switch to AtoM, navigate to jobs scheduler and select job sent from AM

Result: Nominally speaking, the job has reported success. NB: Despite implementing the tmp directory fix (see logs) the cleanup issue is still present. I don't believe, however, that this is related to the core issue:  if we navigate to our linked record 'photograph-album', no object has been associated with the record. 

![image](https://github.com/artefactual/atom/assets/109514137/4a4d0078-b802-4bdc-b481-3d561b8e909a)

5b. Construct an http request to the sword deposit endpoint of our AtoM installation. 
5b-2. I have added a basic file selector element to a blank page, so I can encode the DIP we produced earlier directly as a Blob body to our request, taking advantage of the 'deposit by upload' functionality. I used JS to do this quickly in my browser, but I'm sure postman would work fine. This should let us short-circuit some of the noise related to the upload and cleanup process. 

![image](https://github.com/artefactual/atom/assets/109514137/e345b440-5cef-43ff-8d76-398d3ca7a05a)

5b-3. Send the DIP request, ensure via the browser network panel (or other http client controls) that the request has been sent successfully. 
5b-4. Switch back to AtoM, navigate to the jobs scheduler and select the new job created by our request. 

Result: This time, we've managed to circumvent the cleanup issue and the job returns a complete success report with a green tick. We can see from the report that our record was correctly identified and the request was destructed at the end successfully. Unfortunately, navigating to our target record we can see that once again nothing appears to have happened and no digital objects have been associated. 

![image](https://github.com/artefactual/atom/assets/109514137/032cec1c-823e-49f4-8f37-b8e28a332e07)

In both cases, standard remedial actions do not resolve the issue (reindex, workers, etc). It's definitely possible I'm missing something as well!

### Expected Behavior

In both cases, the DIP contained in our deposit request should be processed by the AtoM server, and the constituent access derivatives should be associated with the identified target description as n child entities, following the structure delineated by the METS structmap. When the DIP process is finished, I should be able to navigate to the target slug on the AtoM site and view the digital objects that were contained in the DIP upload.

### Possible Solution

Unfortunately, I've not been able to identify many possible causes of this issue by tracing the logic in the backend. All I can see for certain is that the flow of the swordWorker is destructed at a certain point, but the ambiguity of the destruct function in this case makes it unclear whether this was because of a failure or success. We have been unable to locate any other logs that might uncover more detail. 

### Context and Notes

Find a post on the AtoM users group I made about the issue here: https://groups.google.com/g/ica-atom-users/c/V4gBzh_eifs

### Version used

AtoM 2.8

### Operating System and version

Ubuntu 20.04 LTS

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by marceloalencar** [comment]
I'm afraid this is an ACL issue, can you try changing the deposit directory from /tmp to something else (like /data) both on AM and AtoM?

**Comment by anvit** [comment]
@Sunday-Crunk closing this issue for now but feel to re-open this if @marceloalencar's suggestion doesn't fix your issue. Also note that `2.8.1` also fixed another DIP upload issue that was due to the Content Security Policy changes introduced in `2.8.0`, so I would recommend updating to `2.8.1` if you aren't using it already
