### ISSUE TITLE
Problem: Image URLs in some example CSVs no longer work

### ISSUE THREAD

**Issue by mcantelon** [artefactual/atom#1781]
### Current Behavior

Importing example CSVs containing URLs to images results in no images being imported due to the URLs no longer working.

Examples:

* `php symfony csv:import lib/task/import/example/isad/example_information_objects_isad.csv`
* `php symfony csv:import lib/task/import/example/rad/example_information_objects_rad.csv`
* `php symfony csv:authority-import lib/task/import/example/authority_records/example_authority_records.csv`

### Expected Behavior

Images should end up getting imported.

### Possible Solution

Use very old image from web.

https://graphics.stanford.edu/courses/cs348b-competition/cs348b-92/newman.monitor.jpg (circa 1992)

### Context and Notes

I use this to test import functionality and these CSVs get used as references for users.

### Default installation culture

en

### PHP version

7.4.3

**Comment by fiver-watson** [comment]
@anvit just FYI - much of the AtoM community, not being developers, get their copy of the CSV templates from the wiki, here: 

* https://wiki.accesstomemory.org/Resources/CSV_templates

If there have been changes to the default templates - even just to update broken links in the sample rows - it would be good to add those to the wiki page!

**Comment by anvit** [comment]
@fiver-watson Thanks! I've added the updated templates to the wiki
