### ISSUE TITLE
Problem: cannot add items to clipboard

### ISSUE THREAD

**Issue by nicdub** [artefactual/atom#1783]
### Current Behavior

**Steps to reproduce the behavior**
1. Find any entry
2. Click Add to Clipboard
3. Nothing is added to the clipboard and we can see this error in the console:
  ```
   Uncaught TypeError: this.items is null
   toggle http://localhost:63001/js/clipboard.js:351
   ```

### Expected Behavior

The item should be added to the clipboard...

### Possible Solution

The problem seems to have appeared in this commit: `Fix clipboard storage behaviour (#1749)` (9cf5ac4ea4c31c2b8179d72a812bbfcf634e530d)

### Version used

AtoM 2.8.1

### Operating System and version

Ubuntu 22.04

### Default installation culture

en

### PHP version

PHP 7.4

**Comment by anvit** [comment]
@nicdub Thanks for reporting this bug!
