### ISSUE TITLE
ERROR: Error: image sevein/gearmand not found

### ISSUE THREAD

**Issue by sepastian** [artefactual/atom#423]
Hello, I'm trying to run Atom using Docker Compose.

Whey doing `docker-compose up -d`, I get

```
ERROR: Error: image sevein/gearmand not found
```

```
$ git branch -a
  qa/2.4.x
* stable/2.3.x
  remotes/origin/HEAD -> origin/qa/2.4.x
:

$ docker-compose --version
docker-compose version 1.8.0-rc2, build c72c966
```

Which gearmand can I use instead?

**Comment by sepastian** [comment]
I updated `docker/docker-compose.dev.yml` to use `pataquets/gearmand/` instead, and it works.

**Comment by sevein** [comment]
Thanks @sepastian and sorry, I shouldn't have deleted that public image! It's back again, hopefully other users won't be affected! See https://hub.docker.com/r/sevein/gearmand/.

**Comment by sepastian** [comment]
Thank you!
