### ISSUE TITLE
Creating a new entity in ATOM

### ISSUE THREAD

**Issue by joaquimpedro** [artefactual/atom#476]
We are using Vagrant to create a new entity with some new fields. The goal is add user metadata with default metadata like ESAD, DC,...

After createad the new entity We'll relate it to an existing metadata. The goal is insert it during the creation of a digital object. 
These custom metadata can also be filled up during DIP Upload by Archivematica. 

1. We need to know the name of the class called during the DIP Upload (which reads the DIP and inserts the metadata). 

2. Following the Symfony 1.4 documentation: (http://symfony.com/legacy/doc/jobeet/1_4/en/03?orm=Propel )When We tried to create a new Class, we had some issues, as shown above: 

	2.1 Change the schema.yml by adding a new table with its fields and keys. DONE
	2.2 - Run: php symfony propel:build --sql to generate .sql according to schema.yml DONE
	2.3 - Run: php symfony tools:purge --demo to recreate the database by inserting the new entity DONE
	2.4 - Run: php symfony propel:build --model to generate the created entity model DONE
	2.5 - Run: php symfony propel:build --all --not-commit to create Forms and Validators >>>> FAIL
		An error occurs:
		build-propel.xml: 474: 20: Duplicate table found: propel.
	2.6 Run: php symfony propel:generate-module qubit thousand QubitMil (project ModuleName ModelName) >>>> FAIL
		But it throws the following error:
		
		PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'QubitMilPeer' not found in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php on line 134

		Warning: call_user_func() expects parameter 1 to be a valid callback, class 'QubitMilPeer' not found in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php on line 134
		PHP Fatal error:  Call to a member function getRelations() on a non-object in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php on line 137

		Fatal error: Call to a member function getRelations() on a non-object in /usr/share/nginx/atom/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php on line 137

I have also posted on Google groups Ica-atom-user
https://groups.google.com/forum/#!topic/ica-atom-users/DZJJj1yuB2E

**Comment by sevein** [comment]
I've responded to your question in the user forum, thanks!
