### ISSUE TITLE
DOCS: Upgrading doc should mention restarting gearman worker

### ISSUE THREAD

**Issue by jasonhildebrand** [artefactual/atom#646]
Hello,
After upgrading to AtoM 2.4.x several functions (finding aids, exports, etc.) were failing with 500 internal server errors.  After checking the logs I realized that the gearman worker simply needed to be restarted.  Bingo.

I thought maybe you could mention this in the "upgrading" doc (https://www.accesstomemory.org/en/docs/2.4/admin-manual/installation/upgrading/)

**Comment by fiver-watson** [comment]
Hi Jason, nice to hear from you!

Good suggestion - I can add this soon. Making a note for myself! I will leave this issue open until I can address it, and will update and close it when I have a link available. Thanks in advance for your patience until I get to this, as I've got a pile of client work to address first! 

Cheers, 
Dan Gillean

**Comment by fiver-watson** [comment]
Hi Jason, 

I added a few things to clarify this. I've noticed that some users seem to miss the parts in our installation docs where we point to the separate page for configuring the job scheduler, so I've added a more explicit warning in both Linux installation docs. 

I also think it's useful to restart all services when upgrading, to ensure the opcode cache and memcached are cleared, in addition to restarting the job scheduler, so I added a section to the upgrading page on restarting services. It's been added in:

https://github.com/artefactual/atom-docs/commit/4a0b500214de307b9a73634d83ae886c11660870

Thanks again for the suggestion!

**Comment by MikeFE** [comment]
I agree with you Dan these are good changes to the docs, +1 here

Mike Gale,
Software Engineer, Artefactual Systems Inc.
http://www.artefactual.com | +1.604.527.2056

**Comment by jasonhildebrand** [comment]
Thanks, Dan.  Good improvements!  I made one comment on the commit, suggesting some stronger wording.

**Comment by fiver-watson** [comment]
Thank you! I've already pushed a change to address your suggestions. :)

**Comment by jasonhildebrand** [comment]
Awesome.  Amazing response time, too! :1st_place_medal:
