### ISSUE TITLE
Upgrade to 2.4.0 - install fails

### ISSUE THREAD

**Issue by taviroquai** [artefactual/atom#714]
Hi,

I'm trying to upgrade from my current instance 2.2.0 to 2.4.0 and install fails after continue on step "Configure Search".

Error from Apache log:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 190867 bytes) in [path]/v2/vendor/symfony/lib/i18n/sfMessageSource.class.php on line 199, referer: http://domain.tld/v2/index.php/sfInstallPlugin/configureSearch

This error complains about memory issues but I don't think this is the problem. This server as 4GB RAM. 

Questions:
1. How much memory can be necessary on install steps?
2. What happens in this step "Configure Search"?
3. Also, What happens in the next step "Load Data"?

Another problem is: after this error, I cannot continue with the instalation by reloading the install page. It seems that it thinks that the install process was complete and throws other errors...

Thanks

**Comment by jraddaoui** [comment]
Hi @taviroquai,

It looks like you're hitting the PHP memory limit in the Load Data step. We recommend at least 512M to run AtoM. Please see (specially the first links to configure PHP):

https://www.accesstomemory.org/en/docs/2.4/admin-manual/installation/execution-limits/#installation-execution-limits

The "Configure Search" step setups the Elasticsearch configuration for your instance and the "Load Data" steps populates the database and the search index with the required initial data.

You may need to recreate the database and restart the process to be able to continue the installation after the PHP configuration has been changed. To trigger the "Check System" step on first page load you could delete the `config/config.php` file from the AtoM folder.

I hope that helps.

**Comment by taviroquai** [comment]
@jraddaoui Setting memory_limit in PHP to 512M solved the problem. Thanks!
