### ISSUE TITLE
Error 500 when trying Export

### ISSUE THREAD

**Issue by taviroquai** [artefactual/atom#715]
Atom Version: 2.4.0 (upgraded from 2.2.0)

**Steps to reproduce in our instance:**
1. Open http://atom.cm-tavira.pt/v2
2. Add record to clipboard
3. Click Go To Clipboard
4. Click Export
5. Click Export

**Logs from Apache (only relevant information):**
[Tue May 22 05:54:23.403182 2018] mod_fcgid: stderr: Unknown record property "informationObject" on "QubitEvent"
[Tue May 22 07:18:12.362738 2018] mod_fcgid: stderr: The template "indexSuccess.xml.php" does not exist or is unreadable in "".
[Tue May 22 11:32:33.673429 2018] mod_fcgid: stderr: Could not connect to 127.0.0.1:4730, referer: http://domain.tld/v2/index.php/object/export?objectType=informationObject

Thanks!

**Comment by jraddaoui** [comment]
Hi @taviroquai,

It looks like the Gearman server is not reachable in that URL. Check the installation docs about it:

https://www.accesstomemory.org/en/docs/2.4/admin-manual/installation/asynchronous-jobs/#installation-asynchronous-jobs

And some user forum questions:

https://groups.google.com/forum/#!topic/ica-atom-users/eYSP6r9zyeM
https://groups.google.com/forum/#!topic/ica-atom-users/2mMKQGNvWdI

Please, could you check and ask this support questions in that forum? You may find a lot of them answered in there.

Thanks!

**Comment by taviroquai** [comment]
@jraddaoui The worker was not installed. Ok I'm new to Atom, next questions will put on the forum. Thanks!
