### ISSUE TITLE
500 error clearing clipboard

### ISSUE THREAD

**Issue by goetzk** [artefactual/atom#800]
Hi,
I spotted a 500 error in our search results and it appears to be caused when Google triggers the "clear clipboard" functionality, specifically the url https://sparc.utas.edu.au/index.php/user/clipboardClear .

Nginx logs the following which appears to come from clipboardClearAction.class.php.
```
2018/11/29 01:31:43 [error] 21583#21583: *45738 FastCGI sent in stderr: "PHP message: Invalid entity type in clear clipboard:" while reading response header from upstream, 
```
However clipboardClearAction.class.php looks like it should include the type, which our error doesn't have.

While not a common error, I also found this result in googles index which even includes an error message.
https://archivesholdings.worldbank.org/user/clipboardClear?sf_culture=es&errorMsg=Invalid+entity+type+in+clear+clipboard%3A+

Points to how I can go about debugging this would be great, as AtoM's logs are empty.

**Comment by mcantelon** [comment]
I've replicated this issue and confirmed this is a bug of sorts. Should be an easy fix. I'm closing this on GitHub and moving it to our Redmine system:

https://projects.artefactual.com/issues/12619
