### ISSUE TITLE
Prevent to overwrite existing "settings.yml" every time the atom container restarts

### ISSUE THREAD

**Issue by ricardodepinho** [artefactual/atom#822]
https://github.com/artefactual/atom/blob/1138ae4022dfd7ecc84f8e20997c0a690c87ad00/docker/bootstrap.php#L68
if (!file_exists(_ATOM_DIR.'/apps/qubit/config/settings.yml')) {

**Comment by jraddaoui** [comment]
Great @ricardodepinho, I really like the idea! I've added a similar fix for the other two config files that may be overwritten in `apps/qubit/config`.

Thanks!

**Comment by fiver-watson** [comment]
Radda's PR can be seen here: https://github.com/artefactual/atom/pull/825

We now have an issue ticket filed in our project tracker, here: https://projects.artefactual.com/issues/12721

In light of this, I am going to close this issue now. Thanks again for the report and the proposed fix, @ricardodepinho !
