### ISSUE TITLE
$resource->getCreators() doesn't return the inherited Creator

### ISSUE THREAD

**Issue by ricardodepinho** [artefactual/atom#824]
https://github.com/artefactual/atom/blob/bf8f8a20bea2efc79c1403d71edabb24496149c7/plugins/sfDcPlugin/modules/sfDcPlugin/templates/_dc.xml.php#L12
$resource->getCreators() seemds to return NULL if the current record creator is not defined. 
It should return the inherited creator from the closest upper levels defined creator.

**Comment by jraddaoui** [comment]
Thanks @ricardodepinho,

Catching-up on some old issues, we have created a Redmine ticket for this matter:

https://projects.artefactual.com/issues/13130

**Comment by jraddaoui** [comment]
This was addressed in 2.6.0: https://github.com/artefactual/atom/pull/982
