### ISSUE TITLE
Comparing a QubitSetting to a string (forgot to call getValue()) arInformationObjectCsvExportJob.class.php

### ISSUE THREAD

**Issue by leigh-ols** [artefactual/atom#858]
https://github.com/artefactual/atom/blob/e787bf406d94e3f8be3405d2b19b40583ee58cff/lib/job/arInformationObjectCsvExportJob.class.php#L84

This code  will never work as `QubitSetting::getByNameAndScope()` returns a `QubitSetting` object, not a string value.
The code should be:

```
QubitSetting::getByNameAndScope('informationobject', 'default_template')->getValue() === 'rad'
```

This issue goes back to 2.4 and possibly further.

**Comment by jraddaoui** [comment]
Hi @leigh-ols,

In PHP there is a magic method called to `__toString()`, which is called internally (if it exists) when an object is evaluated in a string context. The `QubitSetting` class includes such a method in:

https://github.com/artefactual/atom/blob/qa/2.5.x/lib/model/QubitSetting.php#L47-L55

If that setting doesn't exist (something that should be really rare in a normal AtoM installation), comparing a populated string to `null` will always be false. You can test both scenarios with the following script:

```php
<?php

class TestObject
{
  public $value = '';

  public function __construct($value)
  {
    $this->value = $value;
  }

  public function __toString()
  {
    return (string) $this->value;
  }
}

$object = new TestObject('foo');

if ($object == 'foo')
{
  echo "Object with __toString() matches.\n";
}

$object = null;

if ($object != 'foo')
{
  echo "Null object doesn't match.\n";
}
```

**Comment by leigh-ols** [comment]
Wow that's embarrassing sorry!

Yes i'm fully aware of `__toString()` xD

When I tested this yesterday it was failing. It turns out it failed because the gearman workers need to be restarted to load code changes. So when I assumed my worker was running my debug code, it was actually loading the original code.

Sorry to have wasted your time!
