### ISSUE TITLE
AtoM at Docker

### ISSUE THREAD

**Issue by smartexplorate** [artefactual/atom#861]
Hello,

I got the latest Docker based AtoM and build it with docker-compose. At the end I caught an error like that:

ERROR: for docker_atom_worker_1  Cannot start service atom_worker: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/atom/src/docker/entrypoint.sh\": permission denied": unknown

ERROR: for docker_atom_1  Cannot start service atom: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/atom/src/docker/entrypoint.sh\": permission denied": unknown

ERROR: for atom  Cannot start service atom: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/atom/src/docker/entrypoint.sh\": permission denied": unknown

ERROR: for atom_worker  Cannot start service atom_worker: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/atom/src/docker/entrypoint.sh\": permission denied": unknown

Mayby there is any idea what happend? Thanks for an answer.

Kind Regards, Maxim

**Comment by jraddaoui** [comment]
Hi @smartexplorate,

It looks like the permissions of the entry point file are not being preserved. You may be able to fix the issue by making `docker/entrypoint.sh` executable and building the image again.

**Comment by jraddaoui** [comment]
I’m closing this issue because it has been inactive for a few months.

**Comment by jraddaoui** [comment]
I’m closing this issue because it has been inactive for a few months.
