### ISSUE TITLE
Problem: DC metadata not imported into AtoM when METS file has logical structMap

### ISSUE THREAD

**Issue by evelynPM** [artefactual/atom#905]
**Expected behaviour**
AtoM should create an information object out of the Dublin Core metadata entered via the GUI in Archivmatica.

**Current behaviour**
No Information Object is created and none of the DC metadata appear in AtoM. Note that the error may be caused by the presence of a second structMap in the METS file when a transfer is placed in backlog. This is a logical structMap with LABEL="Hierarchical". For transfers run straight through Archivematica without being placed in backlog, there is only the default physical structMap. It's possible that AtoM doesn't know what to do with the fact that the dmdSec is referenced from two structMaps.

**Steps to reproduce**
-In Archivematica, create a transfer and place it in transfer backlog
-In the Appraisal Tab, retrieve the transfer and create a SIP from it
-Enter DC metadata via the GUI
-Create a DIP and upload it to AtoM

**Your environment (version of Archivematica, OS version, etc)**
AM 1.9.1, AtoM 2.4.1

**Comment by fiver-watson** [comment]
Thanks @evelynPM - I've used this to file an issue in Redmine, which remains the AtoM project's primary issue tracker. See: 

* https://projects.artefactual.com/issues/13067

As such, I'm closing this issue so we can follow up there.
