### ISSUE TITLE
Bad branch name on docker compose

### ISSUE THREAD

**Issue by miceno** [artefactual/atom#931]
When building docker images and composing them, the stated branch is `qa/2.5.x`, while the name of the default branch is `qa/2.6.x`.

**Comment by jraddaoui** [comment]
Hi @miceno,

Again, thanks for the report and pull request!

This should be fixed after 9fa52d2. We're testing it internally in `qa/2.6.x` before adding it to `stable/2.5.x` too.

**Comment by jraddaoui** [comment]
Closing as duplicate of https://github.com/artefactual/atom/issues/901.
