### ISSUE TITLE
Atom services should automatically restart

### ISSUE THREAD

**Issue by goetzk** [artefactual/atom#933]
Atom workers are notorious for dieing and causing 500 errors on the frontend.

Please change the default behaviour so services are restarted on failing.

Most recent relevant discussion is the first link, example configuration (copied below for ease of access) is the second.
https://groups.google.com/forum/#!msg/ica-atom-users/bblncVj_Vi0/YRLMWuosCAAJ

https://groups.google.com/forum/#!msg/ica-atom-users/X-07V3RUusw/3sHhpsrzCAAJ

```
[Unit]
Description=AtoM worker
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=12

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=www-data
Group=www-data
WorkingDirectory=/usr/share/nginx/atom
ExecStart=/usr/bin/php -d memory_limit=-1 -d error_reporting="E_ALL" symfony jobs:worker
ExecStop=/bin/kill -s TERM $MAINPID
Restart=always
RestartSec=5
```

**Comment by jraddaoui** [comment]
Related Redmine ticket: https://projects.artefactual.com/issues/13109

**Comment by fiver-watson** [comment]
@goetzk we have added an updated worker config to the 2.5 documentation with the [2.5.2 release](https://wiki.accesstomemory.org/Releases/Release_announcements/Release_2.5.2) made available today. You can see it here: 

* https://www.accesstomemory.org/docs/2.5/admin-manual/installation/asynchronous-jobs/#systemd-ubuntu-16-04-18-04 

It does not mirror exactly the proposed configuration above, but in our installation and upgrade testing we found this to be the most reliable configuration, which should vastly improve the persistence of the atom-worker.

**Comment by goetzk** [comment]
On 29/8/19 03:28, Dan Gillean wrote:
> @goetzk <https://github.com/goetzk> we have added an updated worker 
> config to the 2.5 documentation with the 2.5.2 release 
> <https://wiki.accesstomemory.org/Releases/Release_announcements/Release_2.5.2> 
> made available today.


Thanks Dan!

Karl.
